print("-" * 35)
print("Tugas 1 SISOP Kelas-A")
print("-" * 35)
print("Nama: Vera Febrianti Pakpahan")
print("NPM : 21083010054")
print("-" * 35)
print("notes: ")
print("-" * 35)
print("Halo dunia!")
print("Ini adalah skrip Bash pertamaku di Linux")
