xecho "-----------------------------------"
echo "Tugas 1 SISOP Kelas-A"
echo "-----------------------------------"
echo "Nama : Vera Febrianti Pakpahan"
echo "NPM  : 21083010054"
echo "-----------------------------------"
echo "notes: "
echo "-----------------------------------"
echo -e "Halo dunia!\nIni adalah skrip Bash pertamaku di Linux"
